const items = [
  {
    number: 1,
    version: "1.0.0",
    created: "2023-04-04T20:49:05.000Z",
    modified: "2023-04-04T20:49:28.000Z",
    previousversion: null,
    latestversion: false,
    payload: {
      AnalyticCatalogueNewHeaderEntryData: {
        AnalyticCatalogName: "Carlo Analytic",
        AnalyticNumber: 1,
        AnalyticVersion: "1.0.0",
        AnalyticLanguage: null,
        AnalyticStatus: 1,
        AnalyticActiveFlag: true,
        AnalyticCreatedBy: ["Serrangeli, Carlo (105035002)"],
        AnalyticModifiedBy: null,
        AnalyticCreatedOn: "2023-04-04T20:49:05.000Z",
        AnalyticModifiedOn: "2023-04-04T20:49:05.000Z",
        prev_vers: null,
        next_vers: null,
      },
      AnalyticCatalogueNewSummaryEntryData: {},
      AnalyticCatalogueNewDocumentationEntryData: {},
      AnalyticCatalogueNewExecutionEntryData: {},
      AnalyticCatalogueNewDataIOEntryData: {},
    },
    id: 1,
  },
  {
    number: 1,
    version: "1.0.1",
    created: "2023-04-04T20:49:05.000Z",
    modified: "2023-04-04T20:49:55.000Z",
    previousversion: "1.0.0",
    latestversion: false,
    payload: {
      AnalyticCatalogueNewHeaderEntryData: {
        AnalyticCatalogName: "Carlo Analytic",
        AnalyticNumber: 1,
        AnalyticVersion: "1.0.1",
        AnalyticLanguage: null,
        AnalyticStatus: 2,
        AnalyticActiveFlag: true,
        AnalyticCreatedBy: ["Serrangeli, Carlo (105035002)"],
        AnalyticModifiedBy: ["Belcher, Sebastian (108010253)"],
        AnalyticCreatedOn: "2023-04-04T20:49:05.000Z",
        AnalyticModifiedOn: "2023-04-04T20:49:05.000Z",
        prev_vers: "1.0.0",
        next_vers: null,
      },
      AnalyticCatalogueNewSummaryEntryData: {
        AnalyticDescription: null,
        AtaChapter: null,
        IINPPN: null,
        AnalyticDeveloper: null,
        AnalyticDeveloperOrganization: null,
        AnalyticSMEs: null,
        AnalyticFunctionalOwner: null,
        AnalyticFunctionalOwnerOrganization: null,
        AnalyticCTHs: null,
        AnalyticOutcome: null,
        AnalyticType: null,
        AnalyticConsumingOrganization: null,
        EngineAnalyticChecked: true,
        AttributeEngineFamily: null,
        AttributeEngineModel: null,
        AttributeEngineSeries: null,
        AttributeEngineModule: null,
        AttributeEnginePartName: null,
        AttributeEnginePartNumber: null,
        FailureModeOrCNR: null,
        AttributeEngineServiceBulletin: null,
        AttributeAircraftFamily: null,
        AttributeAircraftModel: null,
        AttributeOther: null,
        AnalyticCFMValueSplit: null,
        AnalyticCFMValueSplitDate: null,
        NotEngineDescription: null,
      },
      AnalyticCatalogueNewDocumentationEntryData: {},
      AnalyticCatalogueNewExecutionEntryData: {},
      AnalyticCatalogueNewDataIOEntryData: {},
    },
    id: 2,
  },
  {
    number: 1,
    version: "1.0.1",
    created: "2023-04-04T20:49:05.000Z",
    modified: "2023-04-04T20:50:20.000Z",
    previousversion: "1.0.0",
    latestversion: false,
    payload: {
      AnalyticCatalogueNewHeaderEntryData: {
        AnalyticCatalogName: "Carlo Analytic 2",
        AnalyticNumber: 1,
        AnalyticVersion: "1.0.1",
        AnalyticLanguage: null,
        AnalyticStatus: 2,
        AnalyticActiveFlag: true,
        AnalyticCreatedBy: ["Serrangeli, Carlo (105035002)"],
        AnalyticModifiedBy: ["Belcher, Sebastian (108010253)"],
        AnalyticCreatedOn: "2023-04-04T20:49:05.000Z",
        AnalyticModifiedOn: "2023-04-04T20:49:05.000Z",
        prev_vers: "1.0.0",
        next_vers: null,
      },
      AnalyticCatalogueNewSummaryEntryData: {
        AnalyticDescription: null,
        AtaChapter: null,
        IINPPN: null,
        AnalyticDeveloper: null,
        AnalyticDeveloperOrganization: null,
        AnalyticSMEs: null,
        AnalyticFunctionalOwner: null,
        AnalyticFunctionalOwnerOrganization: null,
        AnalyticCTHs: null,
        AnalyticOutcome: null,
        AnalyticType: null,
        AnalyticConsumingOrganization: null,
        EngineAnalyticChecked: true,
        AttributeEngineFamily: null,
        AttributeEngineModel: null,
        AttributeEngineSeries: null,
        AttributeEngineModule: null,
        AttributeEnginePartName: null,
        AttributeEnginePartNumber: null,
        FailureModeOrCNR: null,
        AttributeEngineServiceBulletin: null,
        AttributeAircraftFamily: null,
        AttributeAircraftModel: null,
        AttributeOther: null,
        AnalyticCFMValueSplit: null,
        AnalyticCFMValueSplitDate: null,
        NotEngineDescription: null,
      },
      AnalyticCatalogueNewDocumentationEntryData: {},
      AnalyticCatalogueNewExecutionEntryData: {},
      AnalyticCatalogueNewDataIOEntryData: {},
    },
    id: 3,
  },
  {
    number: 1,
    version: "2.0.0",
    created: "2023-04-04T20:49:05.000Z",
    modified: "2023-04-04T20:50:46.000Z",
    previousversion: "1.0.1",
    latestversion: false,
    payload: {
      AnalyticCatalogueNewHeaderEntryData: {
        AnalyticCatalogName: "Carlo Analytic 2",
        AnalyticNumber: 1,
        AnalyticVersion: "2.0.0",
        AnalyticLanguage: [2],
        AnalyticStatus: 2,
        AnalyticActiveFlag: true,
        AnalyticCreatedBy: ["Serrangeli, Carlo (105035002)"],
        AnalyticModifiedBy: ["Belcher, Sebastian (108010253)"],
        AnalyticCreatedOn: "2023-04-04T20:49:05.000Z",
        AnalyticModifiedOn: "2023-04-04T20:49:05.000Z",
        prev_vers: "1.0.1",
        next_vers: null,
      },
      AnalyticCatalogueNewSummaryEntryData: {
        AnalyticDescription: null,
        AtaChapter: null,
        IINPPN: null,
        AnalyticDeveloper: null,
        AnalyticDeveloperOrganization: null,
        AnalyticSMEs: null,
        AnalyticFunctionalOwner: null,
        AnalyticFunctionalOwnerOrganization: null,
        AnalyticCTHs: null,
        AnalyticOutcome: null,
        AnalyticType: null,
        AnalyticConsumingOrganization: null,
        EngineAnalyticChecked: true,
        AttributeEngineFamily: null,
        AttributeEngineModel: null,
        AttributeEngineSeries: null,
        AttributeEngineModule: null,
        AttributeEnginePartName: null,
        AttributeEnginePartNumber: null,
        FailureModeOrCNR: null,
        AttributeEngineServiceBulletin: null,
        AttributeAircraftFamily: null,
        AttributeAircraftModel: null,
        AttributeOther: null,
        AnalyticCFMValueSplit: null,
        AnalyticCFMValueSplitDate: null,
        NotEngineDescription: null,
      },
      AnalyticCatalogueNewDocumentationEntryData: {},
      AnalyticCatalogueNewExecutionEntryData: {},
      AnalyticCatalogueNewDataIOEntryData: {},
    },
    id: 4,
  },
];

module.exports = items;
